<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\HoopsAPI.Domain\HoopsAPI.Domain.csproj" />
      <ProjectReference Include="..\HoopsAPI.Repository\HoopsAPI.Repository.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="DotNetEnv" Version="3.2.0" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.4" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.4" />
      <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.4" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.4" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Implementation\" />
    </ItemGroup>

</Project>
